name: Generate workdir

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    uses: mathieuarthur/leeky/.github/workflows/generate-workdir.yml@main
    secrets:
      LW_LOGIN: ${{ secrets.LW_LOGIN }}
      LW_PASSWORD: ${{ secrets.LW_PASSWORD }}
      CALLER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

