name: Use Leeky Workdir
on: workflow_dispatch
permissions:
  contents: write
jobs:
  workdir:
    uses: mathieuarthur/leeky/.github/workflows/run.yml@v1.0.0
    secrets:
      LW_LOGIN: ${{ secrets.LW_LOGIN }}
      LW_PASSWORD: ${{ secrets.LW_PASSWORD }}
